/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: Empty Application
*              Template for ModusToolbox.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cycfg_pins.h"
#include "cycfg_peripherals.h"
#include "xmc_ccu8.h"
#include "cycfg.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdint.h>

/*-----------------Define Variables------------*/
#ifndef PI
#define PI 3.14159265f
#endif

/*-----------------Settings for PWM Generation------
---the values here match the generated config files---*/
#define PWM_PERIOD (24000U)

#define PWM_COMPARE_MIN (400U)
#define PWM_COMPARE_MAX (23600U)

/*After max and minimum duty cycle values are set, a
modulation index is needed to determine how much the PWM
signals vary based on the rotor position. 
Used for low test values so the duty cycle won't reach 0 or 100%
Angle step defines the step of the PWM change
Step delay is the pause between steps
These parameters were used to test open loop PWM generation*/

#define MOD_INDEX (0.8f)
#define ANGLE_STEP (0.0025f)
#define STEP_DELAY (3000u)

/*---------Function Declarations-----------*/

static inline uint16_t compare_limit(int32_t value)
{
	/*Simple function to check if duty cycle is within set params*/
	if (value < (int32_t)PWM_COMPARE_MIN)
	{
		return PWM_COMPARE_MIN;
	}
	if (value > (int32_t)PWM_COMPARE_MAX)
	{
		return PWM_COMPARE_MAX;
	}
	return (uint16_t)value;
}

static inline uint16_t angle_to_compare(float angle_rad)
{
    /*Takes an electrical angle and converts it to a compare value
    used by the CCU8 unit to modify duty cycle. s is between -1 and 1.
    ---------D = 0.5 + 0.5 * MOD_INDEX * s--------------
    -------------OPEN LOOP IMPLEMENTATION-----------------*/
    float s = sinf(angle_rad);
    float duty = 0.5f + 0.5f * MOD_INDEX * s;
    int32_t compare = (int32_t)(duty * (float)PWM_PERIOD);

    return compare_limit(compare);
}

static inline void update_slice_compare(uint16_t cmp_w, uint16_t cmp_v, uint16_t cmp_u)
{
	/*Updates the CCU8 slices using the declaration in the config files
	slice 0 is phase w
	slice 1 is phase v
	slice 2 is phase u
	shadow transfer updates all slices after the cycle*/
	XMC_CCU8_SLICE_SetTimerCompareMatchChannel1(ccu8_0_ch_0_HW, cmp_w);
	XMC_CCU8_SLICE_SetTimerCompareMatchChannel1(ccu8_0_ch_1_HW, cmp_v);
	XMC_CCU8_SLICE_SetTimerCompareMatchChannel1(ccu8_0_ch_2_HW, cmp_u);
	
	XMC_CCU8_EnableShadowTransfer(ccu8_0_HW, XMC_CCU8_SHADOW_TRANSFER_SLICE_0 | XMC_CCU8_SHADOW_TRANSFER_SLICE_1 | XMC_CCU8_SHADOW_TRANSFER_SLICE_2);
}
/* ---------------- Main ---------------- */
int main(void)
{
    cybsp_init();

    init_cycfg_all();
	/*Beginning of CCU8 TEST*/
	
	float theta = 0.0f;
	
	while(1)
	{
		float theta_u = theta;
		float theta_v = theta - (2.0f * PI / 3.0f); /*120 degree shift*/
		float theta_w = theta - (4.0f * PI / 3.0f); /*240 degree shift*/
		
		uint16_t cmp_u = angle_to_compare(theta_u);
        uint16_t cmp_v = angle_to_compare(theta_v);
        uint16_t cmp_w = angle_to_compare(theta_w);

        update_slice_compare(cmp_w, cmp_v, cmp_u);

        theta += ANGLE_STEP;
        if (theta >= 2.0f * PI)
        {
            theta -= 2.0f * PI;
        }
     }
	/*END OF CCU* TEST*/
    
}


/* [] END OF FILE */